sudo: required
dist: trusty
language: node_js
node_js:
  - 4
  - 6
  - 7
os:
  - osx
  - linux
addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
after_success:
  - npm run dist
notifications:
  irc:
    channels:
      - "chat.freenode.net#datbots"
    template:
      - "%{repository_slug} - %{commit_subject} - %{result} - %{build_url}"
    skip_join: true
    on_success: change
    on_failure: always
