# version format
version: 3.0.{build}-{branch}

# branches to build
branches:
  only:
    - master
    - fix/appveyor

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: false

# Build worker image (VM template)
image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "10"

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - node --version
  - npm --version

test_script:
  - npm run build:prod
  - npm test

build_script:
  - npm run dist

# Don't actually build.
# build: off

artifacts:
  - path: .\dist\*.msi
  - path: .\dist\*.log
