# version format
version: '{branch}-{build}'

# branches to build
branches:
  # whitelist
  only:
    - master
    - fix/appveyor

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: false

# Build worker image (VM template)
image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "10"
# platform:
#   - x86
#   - x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

install:
  - ps: Install-Product node $env:nodejs_version # $env:platform
  - npm install
  - node --version
  - npm --version

build: off
shallow_clone: true
clone_depth: 1

test_script:
  - npm test
  - npm run dist
