# version format
version: 3.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master
    - fix/appveyor

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: false

# Build worker image (VM template)
image: Visual Studio 2017

environment:
  # ELECTRON_ENABLE_STACK_DUMPING: 'true'
  # DEBUG: '*,-nugget*,-eslint*,-extract-zip*,-sumchecker*,-electron-download*,-dependency-check*'
  matrix:
    - nodejs_version: "10"

platform:
  - x86
  - x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - node --version
  - npm --version

test_script:
  - npm run build:prod
  - npm test

build_script:
  - npm run dist
#  - cd dist
#  - msiexec /i "KioskDemoElectron.msi" /l*v "install.log" KIOSK_USERNAME=%username%

# Don't actually build.
# build: off

artifacts:
  - path: .\dist\*.msi
  - path: .\dist\*.log

# RDP for debugging purposes
# init:
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
